import type { Metadata } from "next";
import "./globals.css";
import TopHeader from "@/components/TopHeader";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { CartProvider } from "./Product/context/CartContext";
 
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` `}
      >
        <CartProvider>
        <TopHeader/>
        <Header />
        {children}
        <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
